### ISSUE TITLE
Non, encore transparent, tu veux un screenshot?

### ISSUE THREAD

**Issue by Fsardas** [geleouet/cageot#12]
Non, encore transparent, tu veux un screenshot?

__Originally posted by @Fsardas in https://github.com/geleouet/cageot/issues/9#issuecomment-955325380__

**Comment by geleouet** [comment]
corrigé

**Comment by Fsardas** [comment]
![image](https://user-images.githubusercontent.com/93440162/139541470-70db1a2e-d8a0-445d-9bce-a2739e9bebdd.jpeg)

**Comment by Fsardas** [comment]
![image](https://user-images.githubusercontent.com/93440162/139541487-760360df-7214-4c83-8212-14be60bc529b.jpeg)

**Comment by Fsardas** [comment]
En même temps on peut leur dire que sur mobile ce n'est pas conseillé. Donc pas grave.
