### ISSUE TITLE
Modif de distrib

### ISSUE THREAD

**Issue by Fsardas** [geleouet/cageot#15]
Quand je modifie une distrib (par ex changement de date), ça la ferme (et en effet c'est pas mal) puis le bouton RÉOUVRIR apparaît. 
Je clique dessus... mais en fait ça ne réouvre pas la vente, ça la fait juste remonter en haut, mais il faut ENCORE cliquer sur OUVRIR pour la remettre en activité. 
Est ce normal ? 
(En gros réouvrir ne réouvre pas)

**Comment by Fsardas** [comment]
En fait c'est le bouton RÉOUVRIR qui porte à confusion ; il amène vers l'option d'OUVRIR mais ne réouvre pas..

**Comment by geleouet** [comment]
Comment nommer cet action et cet état ? 
(Quel wording adopter ?)

**Comment by Fsardas** [comment]
Activer ?
