### ISSUE TITLE
Mdp oublié

### ISSUE THREAD

**Issue by Fsardas** [geleouet/cageot#16]
Serait il stp possible de mettre un clic mdp oublié sur la fenêtre de Login?

**Comment by Fsardas** [comment]
Sorry je suis entrain de tester, avais pas vu le lien

**Comment by Fsardas** [comment]
En fait non :) la procédure n'aboutit pas : 
- je reçois le mail avec le code
- je rentre le code et ça me renvoie vers la page pour nouveau mdp
- mais là, j'ai beau saisir un nouveau mdp, il ne le prend pas en compte (l'interface ne bouge pas du tout)

**Comment by geleouet** [comment]
A vérifier je n'ai pas rencontré de soucis
Je recois le code
je le saisis
puis je saisis le nouveau mot de passe
il m'informe que le mot de passe a été modifié
je peux ensuite me connecter avec le nouveau mot de passe

**Comment by Fsardas** [comment]
C'est le 'il m'informe que le mdp a été modifié' que je n'arrive pas à obtenir. J'ai beau cliquer il reste sur la fenêtre commeça ![image](https://user-images.githubusercontent.com/93440162/139572499-3b52938f-d69b-48ec-9275-09051db35c02.png)

**Comment by geleouet** [comment]
trouvé

**Comment by Fsardas** [comment]
Well done !
